### ISSUE TITLE
Bearer token logic is currently unreleased.

### ISSUE THREAD

**Issue by mschaef-da** [innFactory/akka-jwt#2]
Is there a plan to release a new version of this library with the recently added bearer token support?

**Comment by aserrallerios** [comment]
Any word on this? Are we better off publishing our own fork?

**Comment by jona7o** [comment]
Just published https://bintray.com/innfactory/sbt-plugins/akka-jwt/1.2.0
with Scala 2.13 support.

**Comment by aserrallerios** [comment]
It looks like the Scala 2.12 artifact hasn't been published.
